const codesketchTheme = {
	base: 'vs-dark',
	inherit: true,
	rules: [
		{ token: '', foreground: 'e4e4e7', background: '0a0a0b' },
		{ token: 'comment', foreground: '52525b', fontStyle: 'italic' },
		{ token: 'keyword', foreground: '3b82f6' },
		{ token: 'string', foreground: '22c55e' },
		{ token: 'number', foreground: 'f59e0b' },
		{ token: 'type', foreground: '06b6d4' },
		{ token: 'class', foreground: '06b6d4' },
		{ token: 'function', foreground: 'a78bfa' },
		{ token: 'variable', foreground: 'e4e4e7' },
		{ token: 'constant', foreground: 'f59e0b' },
		{ token: 'parameter', foreground: 'e4e4e7' },
		{ token: 'operator', foreground: 'a1a1aa' },
		{ token: 'delimiter', foreground: '71717a' },
		{ token: 'tag', foreground: 'ef4444' },
		{ token: 'attribute.name', foreground: 'f59e0b' },
		{ token: 'attribute.value', foreground: '22c55e' },
		{ token: 'regexp', foreground: 'f97316' },
	],
	colors: {
		'editor.background': '#0a0a0b',
		'editor.foreground': '#e4e4e7',
		'editor.lineHighlightBackground': '#141417',
		'editor.selectionBackground': '#27272a',
		'editor.inactiveSelectionBackground': '#1c1c1f',
		'editorCursor.foreground': '#3b82f6',
		'editorLineNumber.foreground': '#3f3f46',
		'editorLineNumber.activeForeground': '#71717a',
		'editorIndentGuide.background': '#1c1c1f',
		'editorIndentGuide.activeBackground': '#27272a',
		'editor.selectionHighlightBackground': '#27272a80',
		'editorBracketMatch.background': '#27272a',
		'editorBracketMatch.border': '#3f3f46',
		'editorWidget.background': '#141417',
		'editorWidget.border': '#27272a',
		'editorSuggestWidget.background': '#141417',
		'editorSuggestWidget.border': '#27272a',
		'editorSuggestWidget.selectedBackground': '#1c1c1f',
		'editorHoverWidget.background': '#141417',
		'editorHoverWidget.border': '#27272a',
		'input.background': '#0a0a0b',
		'input.border': '#27272a',
		'input.foreground': '#e4e4e7',
		'scrollbar.shadow': '#00000000',
		'scrollbarSlider.background': '#27272a80',
		'scrollbarSlider.hoverBackground': '#3f3f46',
		'scrollbarSlider.activeBackground': '#52525b',
		'minimap.background': '#0a0a0b',
	},
};

export function registerCodesketchTheme(monaco) {
	monaco.editor.defineTheme('codesketch', codesketchTheme);
}

export default codesketchTheme;
